# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\designer\widget_configs.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetConfigs(object):
    def setupUi(self, widgetConfigs):
        widgetConfigs.setObjectName("widgetConfigs")
        widgetConfigs.resize(400, 300)

        self.retranslateUi(widgetConfigs)
        QtCore.QMetaObject.connectSlotsByName(widgetConfigs)

    def retranslateUi(self, widgetConfigs):
        _translate = QtCore.QCoreApplication.translate
        widgetConfigs.setWindowTitle(_translate("widgetConfigs", "Form"))
