# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\designer\widget_ventas.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetVentas(object):
    def setupUi(self, widgetVentas):
        widgetVentas.setObjectName("widgetVentas")
        widgetVentas.resize(400, 300)

        self.retranslateUi(widgetVentas)
        QtCore.QMetaObject.connectSlotsByName(widgetVentas)

    def retranslateUi(self, widgetVentas):
        _translate = QtCore.QCoreApplication.translate
        widgetVentas.setWindowTitle(_translate("widgetVentas", "Form"))
