# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\designer\widget_compras.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetCompras(object):
    def setupUi(self, widgetCompras):
        widgetCompras.setObjectName("widgetCompras")
        widgetCompras.resize(400, 300)

        self.retranslateUi(widgetCompras)
        QtCore.QMetaObject.connectSlotsByName(widgetCompras)

    def retranslateUi(self, widgetCompras):
        _translate = QtCore.QCoreApplication.translate
        widgetCompras.setWindowTitle(_translate("widgetCompras", "Form"))
