# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\designer\widget_materiales.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetMateriales(object):
    def setupUi(self, widgetMateriales):
        widgetMateriales.setObjectName("widgetMateriales")
        widgetMateriales.resize(400, 300)

        self.retranslateUi(widgetMateriales)
        QtCore.QMetaObject.connectSlotsByName(widgetMateriales)

    def retranslateUi(self, widgetMateriales):
        _translate = QtCore.QCoreApplication.translate
        widgetMateriales.setWindowTitle(_translate("widgetMateriales", "Form"))
